import uuid
from typing import List, Optional
from sqlalchemy import Column, String, DateTime, Text, Enum, ForeignKey, Integer, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base
import enum

class PlanStatus(str, enum.Enum):
    PLANNING = "planning"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"

class TaskStatus(str, enum.Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"

class AgentPlan(Base):
    """
    Represents a high-level plan generated by the Planner Agent.
    """
    __tablename__ = "agent_plans"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, index=True, nullable=False)  # Links to Chat Session
    user_goal = Column(Text, nullable=False)
    status = Column(Enum(PlanStatus), default=PlanStatus.PLANNING, nullable=False)
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    tasks = relationship("AgentTask", back_populates="plan", cascade="all, delete-orphan", order_by="AgentTask.sequence")

class AgentTask(Base):
    """
    Represents a specific step/task within a plan, assigned to an Executor Agent.
    """
    __tablename__ = "agent_tasks"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    plan_id = Column(String, ForeignKey("agent_plans.id"), nullable=False)
    
    sequence = Column(Integer, nullable=False)  # Execution order
    name = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    
    # Tool/Agent assignment
    assigned_agent_role = Column(String, default="executor") # planner, executor, reviewer
    expected_tools = Column(JSON, nullable=True) # List of tool names
    
    # Execution State
    status = Column(Enum(TaskStatus), default=TaskStatus.PENDING, nullable=False)
    result = Column(Text, nullable=True)
    error = Column(Text, nullable=True)
    artifacts = Column(JSON, nullable=True) # List of file paths or object references
    
    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    plan = relationship("AgentPlan", back_populates="tasks")
