version: 1
disable_existing_loggers: false

formatters:
  json:
    (): app.core.json_formatter.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout

loggers:
  tiga:
    level: INFO
    handlers: [console]
    propagate: false

  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
