import { ref, computed, watch, onMounted } from 'vue';
import { agentService } from '../services/agentService';
import { STORAGE_KEYS } from '../constants';
import type { Agent, Team, UserScript } from '../types';

/**
 * Manages the selection of agents or teams, and fetches associated user scripts.
 * 
 * @param currentModeId - Ref to the current selected mode (e.g. 'team' or 'solo')
 * @returns Agent selection state and fetch functions
 */
export function useAgentSelection(currentModeId: import('vue').Ref<string | null>) {
  const agents = ref<Agent[]>([]);
  const teams = ref<Team[]>([]);
  const selectedAgentId = ref<string>('');
  const userScripts = ref<UserScript[]>([]);
  const userScriptsLoading = ref(false);
  const userScriptsError = ref('');

  const currentAgent = computed(() => {
    if (currentModeId.value === 'team') {
      return teams.value.find(item => item.id === selectedAgentId.value);
    }
    return agents.value.find(item => item.id === selectedAgentId.value);
  });

  const fetchAgents = async () => {
    try {
      agents.value = await agentService.getAgents();
      // Restore default agent if needed
      if (agents.value.length > 0 && currentModeId.value !== 'team') {
        const currentExists = agents.value.find(a => a.id === selectedAgentId.value);
        if (!selectedAgentId.value || !currentExists) {
          const did = getDefaultAgentId(agents.value);
          selectedAgentId.value = did;
        }
      }
    } catch (e) {
      console.error("Failed to fetch agents", e);
    }
  };

  const fetchTeams = async () => {
    try {
      teams.value = await agentService.getTeams();
    } catch (e) {
      console.error("Failed to fetch teams", e);
    }
  };

  const fetchUserScripts = async (aid: string) => {
    userScriptsError.value = '';
    userScriptsLoading.value = true;
    if (!aid) {
      userScripts.value = [];
      userScriptsLoading.value = false;
      return;
    }
    try {
      const scripts = await agentService.getUserScripts(aid);
      // Filter out the default script generated by backend
      userScripts.value = scripts.filter(s => s.title !== '默认剧本' && s.content.trim() !== '# 默认剧本\n\n这是一个自动生成的剧本模板。');
    } catch (e) {
      userScriptsError.value = '加载失败';
      userScripts.value = [];
    } finally {
      userScriptsLoading.value = false;
    }
  };

  const getDefaultAgentId = (list: Agent[]) => {
    let saved = '';
    try { saved = localStorage.getItem(STORAGE_KEYS.DEFAULT_AGENT_ID) || ''; } catch { }
    if (saved && list.some(a => a.id === saved)) return saved;
    const generic = list.find(a => a.name && (a.name === '通用' || a.name.includes('通用')));
    return generic ? generic.id : (list.length ? list[0].id : '');
  };

  watch(selectedAgentId, (nv) => {
    fetchUserScripts(nv);
    try { if (nv) localStorage.setItem(STORAGE_KEYS.DEFAULT_AGENT_ID, nv); } catch { }
  });

  onMounted(() => {
    fetchAgents();
    fetchTeams();
  });

  return {
    agents,
    teams,
    selectedAgentId,
    currentAgent,
    userScripts,
    userScriptsLoading,
    fetchAgents,
    fetchTeams
  };
}
