"""remove_legacy_workflow_table

Revision ID: 62abb6ca1a42
Revises: a1b2c3d4e5f6
Create Date: 2026-03-28 20:57:22.095945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '62abb6ca1a42'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_lookup'))
        batch_op.drop_index(batch_op.f('ix_workflows_original_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.drop_column('context')

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'), ['knowledge_base_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'))

    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sqlite.JSON(), nullable=True))

    op.create_table('workflows',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('original_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('is_latest', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('definition', sqlite.JSON(), nullable=False),
    sa.Column('change_log', sa.VARCHAR(length=500), nullable=True),
    sa.Column('input_variables', sqlite.JSON(), nullable=True),
    sa.Column('runtime_config', sqlite.JSON(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_original_id'), ['original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_lookup'), ['original_id', 'is_latest'], unique=False)

    # ### end Alembic commands ###
