"""auto migration

Revision ID: 63007e7ac9a0
Revises: 9e3b0feac487
Create Date: 2026-03-23 10:12:10.584431

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '63007e7ac9a0'
down_revision: Union[str, Sequence[str], None] = '9e3b0feac487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _slugify(value: str) -> str:
    value = (value or "").strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text("UPDATE agents SET model_id = :v WHERE model_id IS NULL OR model_id = ''"),
        {"v": "gpt-3.5-turbo"},
    )
    conn.execute(
        sa.text("UPDATE agents SET role = :v WHERE role IS NULL OR role = ''"),
        {"v": "general"},
    )

    existing_mcp_slugs = {
        row[0]
        for row in conn.execute(
            sa.text("SELECT slug FROM mcp_servers WHERE slug IS NOT NULL AND slug != ''")
        ).all()
    }
    mcp_rows = conn.execute(
        sa.text(
            "SELECT id, name FROM mcp_servers WHERE slug IS NULL OR slug = '' ORDER BY id"
        )
    ).mappings().all()
    for row in mcp_rows:
        base = _slugify(row.get("name") or "") or f"mcp-{str(row.get('id'))[:8]}"
        slug = base
        n = 1
        while slug in existing_mcp_slugs:
            n += 1
            slug = f"{base}-{n}"
        existing_mcp_slugs.add(slug)
        conn.execute(
            sa.text("UPDATE mcp_servers SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": row.get("id")},
        )

    existing_skill_slugs = {
        row[0]
        for row in conn.execute(
            sa.text("SELECT slug FROM skills WHERE slug IS NOT NULL AND slug != ''")
        ).all()
    }
    skill_rows = conn.execute(
        sa.text("SELECT id, name FROM skills WHERE slug IS NULL OR slug = '' ORDER BY id")
    ).mappings().all()
    for row in skill_rows:
        base = _slugify(row.get("name") or "") or f"skill-{str(row.get('id'))[:8]}"
        slug = base
        n = 1
        while slug in existing_skill_slugs:
            n += 1
            slug = f"{base}-{n}"
        existing_skill_slugs.add(slug)
        conn.execute(
            sa.text("UPDATE skills SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": row.get("id")},
        )

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'general'"))
        batch_op.create_index('idx_agent_category', ['category'], unique=False)
        batch_op.create_index('idx_agent_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_llm_model_id_llm_models'), 'llm_models', ['llm_model_id'], ['id'])

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('database',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('execution_tools', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_execution_tools_name'), ['name'])

    with op.batch_alter_table('knowledge_chats', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'), ['knowledge_base_id'], unique=False)

    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_vars', sa.JSON(), server_default='{}', nullable=True))
        batch_op.add_column(sa.Column('capabilities_cache', sa.JSON(), server_default='{"tools": [], "resources": [], "prompts": []}', nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('_mcp_slug_author_uc', ['slug', 'author'])
        batch_op.create_index('ix_mcp_official_active', ['is_official', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_is_official'), ['is_official'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_slug'), ['slug'], unique=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('_slug_version_uc', ['slug', 'version'])
        batch_op.create_index(batch_op.f('ix_skills_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_official'), ['is_official'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_public'), ['is_public'], unique=False)
        batch_op.create_index('ix_skills_official_active', ['is_official', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=True)
        batch_op.drop_column('author')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_config', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('extra_metadata', sa.JSON(), server_default='{}', nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_team_leader_id'), ['leader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('original_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('definition',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_index('ix_workflow_lookup', ['original_id', 'is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_original_id'), ['original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_original_id'))
        batch_op.drop_index('ix_workflow_lookup')
        batch_op.alter_column('definition',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('original_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_department_id_departments'), type_='foreignkey')
        batch_op.alter_column('role_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_leader_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('extra_metadata')
        batch_op.drop_column('team_config')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_skills_slug'))
        batch_op.drop_index('ix_skills_official_active')
        batch_op.drop_index(batch_op.f('ix_skills_is_public'))
        batch_op.drop_index(batch_op.f('ix_skills_is_official'))
        batch_op.drop_index(batch_op.f('ix_skills_is_active'))
        batch_op.drop_index(batch_op.f('ix_skills_author_id'))
        batch_op.drop_constraint('_slug_version_uc', type_='unique')
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.TEXT(), nullable=True))

    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_slug'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_is_official'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_is_active'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_author'))
        batch_op.drop_index('ix_mcp_official_active')
        batch_op.drop_constraint('_mcp_slug_author_uc', type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('capabilities_cache')
        batch_op.drop_column('env_vars')

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_knowledge_base_id'))

    with op.batch_alter_table('knowledge_chats', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('execution_tools', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_execution_tools_name'), type_='unique')

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('database',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('port',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_llm_model_id_llm_models'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agents_category'))
        batch_op.drop_index('idx_agent_user_active')
        batch_op.drop_index('idx_agent_category')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'general'"))
        batch_op.alter_column('model_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
