"""auto migration

Revision ID: 8ad0414ba959
Revises: 
Create Date: 2026-03-19 15:24:49.243130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad0414ba959'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_plans'))
    )
    with op.batch_alter_table('agent_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_plans_session_id'), ['session_id'], unique=False)

    op.create_table('agent_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_workflows'))
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('enable_react', sa.Boolean(), nullable=True),
    sa.Column('enable_cot', sa.Boolean(), nullable=True),
    sa.Column('show_tool_calls', sa.Boolean(), nullable=True),
    sa.Column('enable_markdown', sa.Boolean(), nullable=True),
    sa.Column('tools_config', sa.JSON(), nullable=True),
    sa.Column('mcp_config', sa.JSON(), nullable=True),
    sa.Column('skills_config', sa.JSON(), nullable=True),
    sa.Column('knowledge_config', sa.JSON(), nullable=True),
    sa.Column('memory_config', sa.JSON(), nullable=True),
    sa.Column('storage_config', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('idx_agent_category', ['category'], unique=False)
        batch_op.create_index('idx_agent_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('data_query_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_query_sessions'))
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_encrypted', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('encrypted_private_key', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_name'), ['name'], unique=False)

    op.create_table('execution_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_tasks'))
    )
    with op.batch_alter_table('execution_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('execution_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_tools')),
    sa.UniqueConstraint('name', name=op.f('uq_execution_tools_name'))
    )
    op.create_table('graph_export_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_export_configs'))
    )
    with op.batch_alter_table('graph_export_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_export_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_export_configs_name'), ['name'], unique=True)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('advanced_options', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators'))
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_name'), ['name'], unique=False)

    op.create_table('knowledge_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chats'))
    )
    with op.batch_alter_table('knowledge_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chats_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chats_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chats_session_id'), ['session_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('oss_key', sa.String(), nullable=True),
    sa.Column('oss_url', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'UPLOADED', 'INDEXING', 'INDEXED', 'FAILED', name='documentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_id'), ['id'], unique=False)

    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=True),
    sa.Column('supports_tools', sa.Boolean(), nullable=True),
    sa.Column('supports_json_mode', sa.Boolean(), nullable=True),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=True),
    sa.Column('use_agno_cot', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('input_token_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('output_token_price', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_models'))
    )
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_models_id'), ['id'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('transport_type', sa.Enum('STDIO', 'SSE', name='mcptransporttype'), nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('env_vars', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('capabilities_cache', sa.JSON(), server_default='{"tools": [], "resources": [], "prompts": []}', nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('downloads', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'INACTIVE', name='mcpserverstatus'), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('slug', 'author', name='_mcp_slug_author_uc')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index('ix_mcp_official_active', ['is_official', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_is_official'), ['is_official'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_slug'), ['slug'], unique=True)

    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', 'ERROR', name='nodestatus'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_name'), ['name'], unique=False)

    op.create_table('openclaw_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态: PENDING, DISPATCHED, FAILED'),
    sa.Column('original_prompt', sa.Text(), nullable=False, comment='原始用户提示词'),
    sa.Column('parsed_command', sa.JSON(), nullable=False, comment='解析后的命令对象'),
    sa.Column('schedule', sa.DateTime(timezone=True), nullable=True, comment='计划执行时间'),
    sa.Column('target_node_id', sa.String(length=64), nullable=True, comment='目标节点ID'),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='任务会话ID (UUID v4)'),
    sa.Column('keep_alive', sa.Boolean(), nullable=True, comment='是否保持运行时状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('error_log', sa.Text(), nullable=True, comment='错误日志'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_openclaw_tasks'))
    )
    with op.batch_alter_table('openclaw_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_openclaw_tasks_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_openclaw_tasks_session', ['session_id'], unique=False)
        batch_op.create_index('idx_openclaw_tasks_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('uq_openclaw_task', ['original_prompt', 'target_node_id', 'schedule'], unique=True)

    op.create_table('pathway_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secrets_encrypted', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway_sources'))
    )
    with op.batch_alter_table('pathway_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathway_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathway_sources_name'), ['name'], unique=True)

    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('upload_status', sa.String(), nullable=True),
    sa.Column('asr_status', sa.String(), nullable=True),
    sa.Column('summary_status', sa.String(), nullable=True),
    sa.Column('recommendation_status', sa.String(), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('transcription_json', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings'))
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_s3_key'), ['s3_key'], unique=True)

    op.create_table('service_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_categories_slug'), ['slug'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tools_config', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('downloads', sa.Integer(), server_default='0', nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('slug', 'version', name='_slug_version_uc')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_official'), ['is_official'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=False)
        batch_op.create_index('ix_skills_official_active', ['is_official', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=True)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.Enum('COORDINATE', 'ROUTE', 'BROADCAST', 'TASKS', name='teammode'), server_default='coordinate', nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='创建者ID'),
    sa.Column('is_readonly', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('leader_id', sa.String(length=100), nullable=True),
    sa.Column('members', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('team_config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('extra_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_leader_id'), ['leader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_user_id'), ['user_id'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_id', sa.String(length=36), nullable=False, comment='溯源ID'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default='1', nullable=True, comment='是否为当前最新发布版'),
    sa.Column('is_draft', sa.Boolean(), server_default='0', nullable=True, comment='是否为草稿'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False, comment='工作流节点和连线逻辑'),
    sa.Column('change_log', sa.String(length=500), nullable=True, comment='本版本修改了什么'),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('runtime_config', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows'))
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_lookup', ['original_id', 'is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_original_id'), ['original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_agent_role', sa.String(), nullable=True),
    sa.Column('expected_tools', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['agent_plans.id'], name=op.f('fk_agent_tasks_plan_id_agent_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tasks'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('P0', 'P1', 'P2', name='alertlevel'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_alerts_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('llm_model_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('workflow_state', sa.JSON(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_chat_sessions_agent_id_agents')),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], name=op.f('fk_chat_sessions_llm_model_id_llm_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('data_query_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('chart_config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['data_query_sessions.id'], name=op.f('fk_data_query_messages_session_id_data_query_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_query_messages'))
    )
    with op.batch_alter_table('data_query_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_query_messages_id'), ['id'], unique=False)

    op.create_table('node_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('network_in', sa.Float(), nullable=True),
    sa.Column('network_out', sa.Float(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_metrics_node_id_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_metrics'))
    )
    with op.batch_alter_table('node_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_metrics_id'), ['id'], unique=False)

    op.create_table('pathway_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('operators_config', sa.JSON(), nullable=True),
    sa.Column('sinks_config', sa.JSON(), nullable=True),
    sa.Column('dag_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['pathway_sources.id'], name=op.f('fk_pathway_jobs_source_id_pathway_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway_jobs'))
    )
    with op.batch_alter_table('pathway_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathway_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathway_jobs_name'), ['name'], unique=True)

    op.create_table('sub_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_result', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['execution_tasks.id'], name=op.f('fk_sub_tasks_parent_id_execution_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_tasks'))
    )
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_tasks_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_updated_at'), ['updated_at'], unique=False)

    op.create_table('user_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_user_scripts_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_scripts'))
    )
    with op.batch_alter_table('user_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_scripts_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_scripts_id'), ['id'], unique=False)

    op.create_table('user_tool',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_user_tool_tool_id_tools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tool_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tool')),
    sa.UniqueConstraint('user_id', 'tool_id', name='uix_user_tool')
    )
    with op.batch_alter_table('user_tool', schema=None) as batch_op:
        batch_op.create_index('ix_user_tool_user_id_tool_id', ['user_id', 'tool_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('execution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sub_task_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_tasks.id'], name=op.f('fk_execution_logs_sub_task_id_sub_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_logs'))
    )
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('importance', sa.String(), nullable=False),
    sa.Column('content_enc', sa.Text(), nullable=True),
    sa.Column('before_state_enc', sa.Text(), nullable=True),
    sa.Column('after_state_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_task_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_logs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_logs'))
    )
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_importance'), ['importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_logs_task_id'), ['task_id'], unique=False)

    op.create_table('task_qas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('question_enc', sa.Text(), nullable=False),
    sa.Column('answer_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_qas_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_qas_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_qas'))
    )
    with op.batch_alter_table('task_qas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_qas_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_qas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_qas_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_qas_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_qas_user_id'), ['user_id'], unique=False)

    op.create_table('task_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_task_versions_assignee_id_users')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_task_versions_changed_by_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_versions_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_versions'))
    )
    with op.batch_alter_table('task_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_versions_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_task_versions_task_version', ['task_id', 'version'], unique=True)
        batch_op.create_index(batch_op.f('ix_task_versions_version'), ['version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_versions_version'))
        batch_op.drop_index('ix_task_versions_task_version')
        batch_op.drop_index(batch_op.f('ix_task_versions_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_versions_changed_by'))
        batch_op.drop_index(batch_op.f('ix_task_versions_assignee_id'))

    op.drop_table('task_versions')
    with op.batch_alter_table('task_qas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_qas_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_qas_updated_at'))
        batch_op.drop_index(batch_op.f('ix_task_qas_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_qas_id'))
        batch_op.drop_index(batch_op.f('ix_task_qas_created_at'))

    op.drop_table('task_qas')
    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_logs_importance'))
        batch_op.drop_index(batch_op.f('ix_task_logs_id'))
        batch_op.drop_index(batch_op.f('ix_task_logs_expires_at'))
        batch_op.drop_index(batch_op.f('ix_task_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_task_logs_action_type'))

    op.drop_table('task_logs')
    op.drop_table('execution_logs')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_tool', schema=None) as batch_op:
        batch_op.drop_index('ix_user_tool_user_id_tool_id')

    op.drop_table('user_tool')
    with op.batch_alter_table('user_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_scripts_id'))
        batch_op.drop_index(batch_op.f('ix_user_scripts_agent_id'))

    op.drop_table('user_scripts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_name'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_tasks_status'))

    op.drop_table('sub_tasks')
    with op.batch_alter_table('pathway_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathway_jobs_name'))
        batch_op.drop_index(batch_op.f('ix_pathway_jobs_id'))

    op.drop_table('pathway_jobs')
    with op.batch_alter_table('node_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_metrics_id'))

    op.drop_table('node_metrics')
    with op.batch_alter_table('data_query_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_query_messages_id'))

    op.drop_table('data_query_messages')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_id'))

    op.drop_table('alerts')
    op.drop_table('agent_tasks')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_original_id'))
        batch_op.drop_index('ix_workflow_lookup')

    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_name'))

    op.drop_table('tools')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_name'))
        batch_op.drop_index(batch_op.f('ix_team_leader_id'))
        batch_op.drop_index(batch_op.f('ix_team_id'))

    op.drop_table('team')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_slug'))
        batch_op.drop_index('ix_skills_official_active')
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_is_public'))
        batch_op.drop_index(batch_op.f('ix_skills_is_official'))
        batch_op.drop_index(batch_op.f('ix_skills_is_active'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))
        batch_op.drop_index(batch_op.f('ix_skills_author_id'))

    op.drop_table('skills')
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_categories_slug'))

    op.drop_table('service_categories')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_s3_key'))
        batch_op.drop_index(batch_op.f('ix_recordings_parent_id'))
        batch_op.drop_index(batch_op.f('ix_recordings_id'))
        batch_op.drop_index(batch_op.f('ix_recordings_filename'))

    op.drop_table('recordings')
    with op.batch_alter_table('pathway_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathway_sources_name'))
        batch_op.drop_index(batch_op.f('ix_pathway_sources_id'))

    op.drop_table('pathway_sources')
    with op.batch_alter_table('openclaw_tasks', schema=None) as batch_op:
        batch_op.drop_index('uq_openclaw_task')
        batch_op.drop_index('idx_openclaw_tasks_status_created')
        batch_op.drop_index('idx_openclaw_tasks_session')
        batch_op.drop_index('idx_openclaw_tasks_created_at')

    op.drop_table('openclaw_tasks')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_name'))
        batch_op.drop_index(batch_op.f('ix_nodes_group'))

    op.drop_table('nodes')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_slug'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_is_official'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_is_active'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_category'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_author'))
        batch_op.drop_index('ix_mcp_official_active')

    op.drop_table('mcp_servers')
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_models_id'))

    op.drop_table('llm_models')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_filename'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('knowledge_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chats_session_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chats_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chats_doc_id'))

    op.drop_table('knowledge_chats')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_name'))
        batch_op.drop_index(batch_op.f('ix_indicators_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_indicators_id'))
        batch_op.drop_index(batch_op.f('ix_indicators_group'))

    op.drop_table('indicators')
    with op.batch_alter_table('graph_export_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_export_configs_name'))
        batch_op.drop_index(batch_op.f('ix_graph_export_configs_id'))

    op.drop_table('graph_export_configs')
    op.drop_table('execution_tools')
    with op.batch_alter_table('execution_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_execution_tasks_status'))

    op.drop_table('execution_tasks')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_name'))
        batch_op.drop_index(batch_op.f('ix_data_sources_id'))

    op.drop_table('data_sources')
    op.drop_table('data_query_sessions')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index(batch_op.f('ix_agents_category'))
        batch_op.drop_index('idx_agent_user_active')
        batch_op.drop_index('idx_agent_category')

    op.drop_table('agents')
    op.drop_table('agent_workflows')
    with op.batch_alter_table('agent_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_plans_session_id'))

    op.drop_table('agent_plans')
    # ### end Alembic commands ###
