"""update_user_models

Revision ID: 9e3b0feac487
Revises: 3b1d2d12c1c0
Create Date: 2026-03-21 15:22:08.916812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3b0feac487'
down_revision: Union[str, Sequence[str], None] = '3b1d2d12c1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_task_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('extend', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_task_logs'))
    )
    with op.batch_alter_table('async_task_logs', schema=None) as batch_op:
        batch_op.create_index('ix_async_task_logs_task_created', ['task_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_async_task_logs_task_id'), ['task_id'], unique=False)

    op.create_table('async_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_tasks'))
    )
    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_async_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_async_tasks_status'), ['status'], unique=False)
        batch_op.create_index('ix_async_tasks_status_deleted', ['status', 'deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_async_tasks_task_type'), ['task_type'], unique=False)
        batch_op.create_index('ix_async_tasks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_async_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('leader', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('user_market_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_market_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_market_items')),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='uix_user_market_items')
    )
    with op.batch_alter_table('user_market_items', schema=None) as batch_op:
        batch_op.create_index('ix_user_market_items_user_type_id', ['user_id', 'item_type', 'item_id'], unique=False)

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_system_configs_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('role_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_department_id_departments'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_department_id_departments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('status')
        batch_op.drop_column('department_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('phone')

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_key'))
        batch_op.create_index(batch_op.f('ix_system_configs_key'), ['key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_system_configs_key'), ['key'])

    with op.batch_alter_table('user_market_items', schema=None) as batch_op:
        batch_op.drop_index('ix_user_market_items_user_type_id')

    op.drop_table('user_market_items')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_async_tasks_user_id'))
        batch_op.drop_index('ix_async_tasks_user_created')
        batch_op.drop_index(batch_op.f('ix_async_tasks_task_type'))
        batch_op.drop_index('ix_async_tasks_status_deleted')
        batch_op.drop_index(batch_op.f('ix_async_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_async_tasks_name'))

    op.drop_table('async_tasks')
    with op.batch_alter_table('async_task_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_async_task_logs_task_id'))
        batch_op.drop_index('ix_async_task_logs_task_created')

    op.drop_table('async_task_logs')
    # ### end Alembic commands ###
