import logging
import base64
import tempfile
import os
from uuid import uuid4
from typing import Optional, Union
from agno.tools import Toolkit
from agno.tools.function import ToolResult
from agno.media import Image
from app.services.sandbox.codebox import codebox_service

logger = logging.getLogger(__name__)

class SandboxTools(Toolkit):
    _name = "sandbox"
    _label = "代码沙箱 (E2B)"
    _description = "安全执行 Python 代码和 Shell 命令"
    """
    与 E2B 沙箱环境交互的工具，支持代码执行、Shell 命令和文件管理。
    """

    def __init__(self, session_id: Optional[str] = None):
        super().__init__(name="sandbox_tools")
        self.session_id = session_id
        self.register(self.run_code)
        self.register(self.run_shell)
        self.register(self.read_file)
        self.register(self.write_file)
        self.register(self.list_files)

    async def run_code(self, code: str, language: str = "python") -> Union[str, ToolResult]:
        """
        Executes code in the sandbox environment.
        
        Args:
            code: The code to execute.
            language: The programming language (default: python).
            
        Returns:
            The output of the code execution (stdout + stderr) or error message.
            If images are generated, returns a ToolResult with image artifacts.
        """
        try:
            # Currently only Python is fully supported by the execute method wrapper
            # For other languages, we might need to use shell commands or extend execute
            if language.lower() != "python":
                # Fallback to shell execution for non-python if possible, or implement specific runners
                # For now, let's warn or try to run as python if it looks like python
                pass

            result = await codebox_service.execute(code, session_id=self.session_id)
            
            output_text = []
            images = []
            
            if result.get("status") == "success":
                output_text.append(result.get("content", ""))
                
                # Handle files (images)
                files = result.get("files", [])
                if files:
                    files_desc = []
                    for file_info in files:
                        file_name = file_info.get("name", "unknown_file")
                        files_desc.append(f"File generated: {file_name}")
                        
                        # Check if it's an image
                        if file_info.get("type", "").startswith("image/"):
                            try:
                                content_b64 = file_info.get("content")
                                if content_b64:
                                    # Decode base64
                                    image_data = base64.b64decode(content_b64)
                                    
                                    # Save to UPLOADS_DIR for frontend access
                                    from pathlib import Path
                                    backend_dir = Path(__file__).resolve().parents[5]
                                    uploads_dir = backend_dir / "data" / "storage"
                                    uploads_dir.mkdir(parents=True, exist_ok=True)
                                    
                                    # Use the file_name generated by e2b_sandbox.py
                                    file_path = uploads_dir / file_name
                                    with open(file_path, "wb") as f:
                                        f.write(image_data)
                                        
                                    public_url = f"/uploads/{file_name}"
                                    
                                    # Create Image object
                                    image_id = str(uuid4())
                                    
                                    images.append(Image(
                                        id=image_id,
                                        url=public_url,
                                        original_prompt=f"Generated from code execution: {file_name}"
                                    ))
                                    logger.info(f"Created image artifact: {file_path}")
                                    
                                    # Explicitly tell the LLM the markdown URL to use
                                    files_desc.append(f"Image is accessible at: {public_url} (You can display it using markdown: ![chart]({public_url}))")
                                    # We don't append the original "File generated" message to avoid confusion
                                    files_desc.pop() # remove the generic message added earlier
                            except Exception as img_err:
                                logger.error(f"Failed to process image {file_name}: {img_err}")
                                files_desc.append(f"(Failed to process image: {img_err})")

                    output_text.append("\n".join(files_desc))
            else:
                output_text.append(f"Error: {result.get('content', 'Unknown error')}")
            
            final_output = "\n".join(output_text)
            
            if images:
                return ToolResult(
                    content=final_output,
                    images=images
                )
            else:
                return final_output

        except Exception as e:
            return f"Execution failed: {str(e)}"

    async def run_shell(self, command: str) -> str:
        """
        Executes a shell command in the sandbox.
        
        Args:
            command: The shell command to run (e.g., 'ls -la', 'pip install numpy').
            
        Returns:
            The standard output and standard error of the command.
        """
        try:
            # Efficient way: Use python's subprocess in the sandbox
            # We wrap it to ensure we get stdout/stderr
            wrapper_code = f"""
import subprocess
try:
    result = subprocess.run('{command}', shell=True, capture_output=True, text=True, timeout=60)
    print(result.stdout)
    if result.stderr:
        print('STDERR:', result.stderr)
except Exception as e:
    print(f"Shell execution error: {{e}}")
"""
            # Note: run_shell returns string, so we just take the content if run_code returns ToolResult
            res = await self.run_code(wrapper_code)
            if isinstance(res, ToolResult):
                return res.content
            return res
        except Exception as e:
            return f"Shell command failed: {str(e)}"

    async def read_file(self, path: str) -> str:
        """
        Reads the content of a file from the sandbox.
        
        Args:
            path: The absolute path to the file.
            
        Returns:
            The content of the file.
        """
        try:
            wrapper_code = f"""
try:
    with open('{path}', 'r') as f:
        print(f.read())
except Exception as e:
    print(f"Error reading file: {{e}}")
"""
            res = await self.run_code(wrapper_code)
            if isinstance(res, ToolResult):
                return res.content
            return res
        except Exception as e:
            return f"Failed to read file: {str(e)}"

    async def write_file(self, path: str, content: str) -> str:
        """
        Writes content to a file in the sandbox.
        
        Args:
            path: The absolute path to the file.
            content: The content to write.
            
        Returns:
            Success message or error.
        """
        try:
            await codebox_service.upload_file(self.session_id, path, content)
            return f"Successfully wrote to {path}"
        except Exception as e:
            return f"Failed to write file: {str(e)}"

    async def list_files(self, path: str = ".") -> str:
        """
        Lists files in a directory.
        
        Args:
            path: The directory path (default: current directory).
            
        Returns:
            List of files.
        """
        return await self.run_shell(f"ls -la {path}")
